---
name: FlowCrafter
description: Run FlowCrafter and update the GitHub Actions

runs:
  using: "composite"
  steps:
    - name: Install FlowCrafter
      shell: bash
      run: "curl --proto '=https' --tlsv1.2 -LsSf https://github.com/jdno/flowcrafter/releases/download/v0.3.0/flowcrafter-installer.sh | sh"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: flowcrafter update
      shell: bash
      run: "flowcrafter update"

    - name: Check if workflows changed
      id: check
      shell: bash
      run: |
        if git diff --exit-code --quiet; then
          echo 'No changes detected'
          echo "changed=false" >> $GITHUB_OUTPUT
        else
          echo 'Changes detected'
          echo "changed=true" >> $GITHUB_OUTPUT
        fi

    - name: Create pull request
      uses: peter-evans/create-pull-request@v5
      if: steps.check.outputs.changed == 'true' && github.event_name != 'push' && github.event_name != 'pull_request'
      with:
        add-paths: ".github/workflows"
        branch: "flowcrafter/update"
        commit-message: "Update GitHub Actions"
        title: "Update GitHub Actions"
        body: |
          This pull request was automatically created by FlowCrafter after
          running `flowcrafter update` on the repository.
