[package]
name = "flowcrafter"

version = "0.1.0"
edition = "2021"

license = "MIT OR Apache-2.0"
description = "Create and manage workflows for GitHub Actions"
repository = "https://github.com/jdno/flowcrafter"

default-run = "flowcrafter"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["cli"]
cli = [
    "clap",
    "serde",
    "serde_yaml",
]

[[bin]]
name = "flowcrafter"
required-features = ["cli"]

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
base64 = "0.21.4"
clap = { version = "4.4.4", optional = true, features = ["derive"] }
octocrab = "0.30.1"
serde = { version = "1.0.188", optional = true, features = ["derive"] }
serde_yaml = { version = "0.9.25", optional = true }
thiserror = "1.0.48"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
typed-builder = "0.16.2"
url = "2.3.1"

[dev-dependencies]
indoc = "2.0.4"
mockito = "1.2.0"
serde_json = "1.0.107"
tempfile = "3.8.0"
serde_yaml = { version = "0.9.25" }
