[package]
name = "flowcrafter"

version = "0.1.0"
edition = "2021"

license = "MIT OR Apache-2.0"
description = "Create and manage workflows for GitHub Actions"
repository = "https://github.com/jdno/flowcrafter"

default-run = "flowcrafter"

# See more keys and their definitions at
# https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["cli"]
cli = [
    "clap",
    "serde",
    "serde_yaml",
]

[[bin]]
name = "flowcrafter"
required-features = ["cli"]

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
base64 = "0.21.0"
clap = { version = "4.2.7", optional = true, features = ["derive"] }
octocrab = "0.22.0"
serde = { version = "1.0.163", optional = true, features = ["derive"] }
serde_yaml = { version = "0.9.21", optional = true }
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
typed-builder = "0.14.0"
url = "2.3.1"

[dev-dependencies]
indoc = "2.0.4"
mockito = "1.0.2"
serde_json = "1.0.96"
tempfile = "3.5.0"
serde_yaml = { version = "0.9.21" }
